// Rendering. Two audiences: a compact view for an agent's terminal, and PROGRESS.md,
// the handoff board a human or a fresh session reads to see who is doing what.
import { loadConfig } from "./config.ts";
import { isProcessAlive, listAgents, shortId } from "./identity.ts";
import { isLeaseStale, listLeases } from "./lease.ts";
import type { Lease } from "./lease.ts";
import { progressPath } from "./paths.ts";
import { lastNext, listTasks } from "./task.ts";
import type { Task, TaskStatus } from "./task.ts";
import { nowIso, writeJsonAtomic } from "./store.ts";
import * as fs from "node:fs";
import * as path from "node:path";

/** Board order: what is moving, then what is available, then the archive. */
const DISPLAY_ORDER: TaskStatus[] = [
  "in_progress",
  "blocked",
  "review",
  "ready",
  "backlog",
  "done",
  "abandoned",
];

const STATUS_LABEL: Record<TaskStatus, string> = {
  in_progress: "In progress",
  blocked: "Blocked",
  review: "In review",
  ready: "Ready to claim",
  backlog: "Backlog",
  done: "Done",
  abandoned: "Abandoned",
};

function byPriority(a: Task, b: Task): number {
  if (a.priority !== b.priority) return a.priority - b.priority;
  return a.id.localeCompare(b.id);
}

function group(tasks: Task[]): Map<TaskStatus, Task[]> {
  const grouped = new Map<TaskStatus, Task[]>();
  for (const status of DISPLAY_ORDER) grouped.set(status, []);
  for (const task of tasks) {
    const bucket = grouped.get(task.status);
    if (bucket !== undefined) bucket.push(task);
  }
  for (const bucket of grouped.values()) bucket.sort(byPriority);
  return grouped;
}

function describeOwner(task: Task): string {
  return task.owner === null ? "unowned" : `${task.owner.agentName} (${shortId(task.owner.agentId)})`;
}

function ageMinutes(iso: string): number {
  const delta = Date.now() - Date.parse(iso);
  return Number.isFinite(delta) ? Math.max(0, Math.round(delta / 60000)) : 0;
}

/** Compact terminal board. */
export function renderBoard(options: { agentId?: string | null } = {}): string {
  const config = loadConfig();
  const now = Date.now();
  const tasks = listTasks();
  const grouped = group(tasks);
  const lines: string[] = [];

  const open = tasks.filter((task) => task.status !== "done" && task.status !== "abandoned");
  lines.push(`Harness board — ${open.length} open, ${tasks.length} total`);

  for (const status of DISPLAY_ORDER) {
    const bucket = grouped.get(status) ?? [];
    if (bucket.length === 0) continue;
    // The archive gets a count, not a listing.
    if (status === "done" || status === "abandoned") {
      lines.push(`  ${STATUS_LABEL[status]}: ${bucket.length}`);
      continue;
    }
    lines.push("");
    lines.push(`${STATUS_LABEL[status]} (${bucket.length})`);
    for (const task of bucket) {
      const mine = options.agentId !== undefined &&
        options.agentId !== null &&
        task.owner?.agentId === options.agentId;
      const marker = mine ? "*" : " ";
      lines.push(`${marker} ${task.id}  p${task.priority}  ${task.title}`);
      if (task.status === "in_progress") {
        lines.push(`      owner: ${describeOwner(task)} for ${ageMinutes(task.owner?.since ?? task.updatedAt)}m`);
      }
      if (task.scopes.length > 0) lines.push(`      scopes: ${task.scopes.join(", ")}`);
      const next = lastNext(task);
      if (next !== null) lines.push(`      next: ${next}`);
      if (task.attempts > 0) lines.push(`      reclaimed ${task.attempts}x`);
    }
  }

  const leases = listLeases();
  const live = leases.filter((lease) => !isLeaseStale(lease, config, now));
  const stale = leases.length - live.length;
  lines.push("");
  lines.push(`Leases: ${live.length} live${stale > 0 ? `, ${stale} reclaimable (run: reap)` : ""}`);
  for (const lease of live) {
    lines.push(`  ${lease.scope} — ${lease.agentName} (${lease.taskId ?? "no task"}), ${ageMinutes(lease.heartbeatAt)}m since heartbeat`);
  }

  return lines.join("\n");
}

function markdownTable(rows: string[][], header: string[]): string[] {
  const out = [`| ${header.join(" | ")} |`, `| ${header.map(() => "---").join(" | ")} |`];
  for (const row of rows) out.push(`| ${row.join(" | ")} |`);
  return out;
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

/** The durable handoff board. Regenerated on every state change; never hand-edited. */
export function renderProgressMarkdown(): string {
  const config = loadConfig();
  const now = Date.now();
  const tasks = listTasks();
  const grouped = group(tasks);
  const lines: string[] = [];

  lines.push("# Harness progress board");
  lines.push("");
  lines.push("Generated by `node .claude/harness/cli.ts board`. Do not hand-edit — the");
  lines.push("harness rewrites this file. Change tasks through the CLI instead.");
  lines.push("");
  lines.push(`Last updated: ${nowIso()}`);
  lines.push("");

  for (const status of DISPLAY_ORDER) {
    const bucket = grouped.get(status) ?? [];
    if (bucket.length === 0) continue;
    lines.push(`## ${STATUS_LABEL[status]} (${bucket.length})`);
    lines.push("");

    if (status === "done" || status === "abandoned") {
      for (const task of bucket) lines.push(`- ${task.id} — ${escapeCell(task.title)}`);
      lines.push("");
      continue;
    }

    const rows = bucket.map((task) => [
      task.id,
      `p${task.priority}`,
      escapeCell(task.title),
      escapeCell(describeOwner(task)),
      task.scopes.length === 0 ? "—" : escapeCell(task.scopes.join("<br>")),
      escapeCell(lastNext(task) ?? "—"),
    ]);
    lines.push(...markdownTable(rows, ["Task", "Pri", "Title", "Owner", "Scopes", "Next step"]));
    lines.push("");
  }

  const leases = listLeases().filter((lease: Lease) => !isLeaseStale(lease, config, now));
  lines.push(`## Live leases (${leases.length})`);
  lines.push("");
  if (leases.length === 0) {
    lines.push("No scope is currently locked.");
  } else {
    lines.push(
      ...markdownTable(
        leases.map((lease) => [
          escapeCell(lease.scope),
          escapeCell(lease.agentName),
          lease.taskId ?? "—",
          `${ageMinutes(lease.heartbeatAt)}m ago`,
        ]),
        ["Scope", "Held by", "Task", "Last heartbeat"],
      ),
    );
  }
  lines.push("");

  const agents = listAgents().sort((a, b) => b.heartbeatAt.localeCompare(a.heartbeatAt));
  lines.push(`## Agents (${agents.length})`);
  lines.push("");
  if (agents.length === 0) {
    lines.push("No agent has registered yet.");
  } else {
    lines.push(
      ...markdownTable(
        agents.map((agent) => [
          escapeCell(agent.name),
          shortId(agent.agentId),
          isProcessAlive(agent.pid) ? "alive" : "gone",
          `${ageMinutes(agent.heartbeatAt)}m ago`,
        ]),
        ["Name", "Id", "Process", "Last seen"],
      ),
    );
  }
  lines.push("");

  return lines.join("\n");
}

export function writeProgress(): string {
  const file = progressPath();
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, renderProgressMarkdown(), "utf8");
  return file;
}

/** Machine-readable snapshot for anything that would rather parse than scrape. */
export function boardJson(): unknown {
  const config = loadConfig();
  const now = Date.now();
  return {
    generatedAt: nowIso(),
    tasks: listTasks(),
    leases: listLeases().map((lease) => ({ ...lease, stale: isLeaseStale(lease, config, now) })),
    agents: listAgents().map((agent) => ({ ...agent, alive: isProcessAlive(agent.pid) })),
  };
}

/** Exported for the self-test, which asserts the snapshot round-trips as JSON. */
export function writeBoardJson(file: string): void {
  writeJsonAtomic(file, boardJson());
}
